### ISSUE TITLE
swagger2markup plugin isn't triggered

### ISSUE THREAD

**Issue by pgtelus** [Swagger2Markup/swagger2markup-maven-project-template#2]
HI Rob, I'm not overly familiar with maven so I don't know if this is WAI or not.  I would have expected "mvn clean install" would generated the HTML / PDF sample doc.  However, it doesn't ... I have to manually run the swagger2markup goal "mvn swagger2markup:conertSwagger2markup" first.  After that "mvn install" generates the HTML / PDF docs.

Thanks for your efforts here, I expect this tool is going to be very helpful!

**Comment by pgtelus** [comment]
This diff makes it work as I would have expected.

[patch.txt](https://github.com/Swagger2Markup/swagger2markup-maven-project-template/files/321301/patch.txt)

**Comment by RobWin** [comment]
Hi,
thx. Could you please create a Pull Request with your change? If you are new to GitHub, see https://help.github.com/articles/using-pull-requests/.

If you like and use Swagger2markup, we would love to get your GitHub Stars.

**Comment by pgtelus** [comment]
np, done
